module Hagbard
  TRIGRAMS = [
    { :bin => '111', :name => 'The Creative', :number => "1" },
    { :bin => '110', :name => 'The Joyous', :number => "2" },
    { :bin => '101', :name => 'The Clinging', :number => "3" },
    { :bin => '100', :name => 'The Arousing', :number => "4" },
    { :bin => '011', :name => 'The Gentle', :number => "5" },
    { :bin => '010', :name => 'The Abysmal', :number => "6" },
    { :bin => '001', :name => 'Keeping Still', :number => "7" },
    { :bin => '000', :name => 'The Receptive', :number => "8" }
  ]

  HEXAGRAMS = [
    { :bin => '111111', :number => "1", :name => 'Ch\'ien / The Creative' },
    { :bin => '000000', :number => "2", :name => 'K\'un / The Receptive' },
    { :bin => '100010', :number => "3", :name => 'Chun / Difficulty at the Beginning' },
    { :bin => '010001', :number => "4", :name => 'Meng / Youthful Folly' },
    { :bin => '111010', :number => "5", :name => 'Hsu / Waiting (Nourishment)' },
    { :bin => '010111', :number => "6", :name => 'Sung / Conflict' },
    { :bin => '010000', :number => "7", :name => 'Shih / The Army' },
    { :bin => '000010', :number => "8", :name => 'Pi / Holding Together [union]' },
    { :bin => '111011', :number => "9", :name => 'Hsiao Ch\'u / The Taming Power of the Small' },
    { :bin => '110111', :number => "10", :name => 'Lu / Treading [conduct]' },
    { :bin => '111000', :number => "11", :name => 'T\'ai / Peace' },
    { :bin => '000111', :number => "12", :name => 'P\'i / Standstill [Stagnation]' },
    { :bin => '101111', :number => "13", :name => 'T\'ung Jen / Fellowship with Men' },
    { :bin => '111101', :number => "14", :name => 'Ta Yu / Possession in Great Measure' },
    { :bin => '001000', :number => "15", :name => 'Ch\'ien / Modesty' },
    { :bin => '000100', :number => "16", :name => 'Yu / Enthusiasm' },
    { :bin => '100110', :number => "17", :name => 'Sui / Following' },
    { :bin => '011001', :number => "18", :name => 'Ku / Work on what has been spoiled [Decay]' },
    { :bin => '110000', :number => "19", :name => 'Lin / Approach' },
    { :bin => '000011', :number => "20", :name => 'Kuan / Contemplation (View)' },
    { :bin => '100101', :number => "21", :name => 'Shih Ho / Biting Through' },
    { :bin => '101001', :number => "22", :name => 'Pi / Grace' },
    { :bin => '000001', :number => "23", :name => 'Po / Splitting Apart' },
    { :bin => '100000', :number => "24", :name => 'Fu / Return (The Turning Point)' },
    { :bin => '100111', :number => "25", :name => 'Wu Wang / Innocence (The Unexpected)' },
    { :bin => '111001', :number => "26", :name => 'Ta Ch\'u / The Taming Power of the Great' },
    { :bin => '100001', :number => "27", :name => 'I / Corners of the Mouth (Providing Nourishment)' },
    { :bin => '011110', :number => "28", :name => 'Ta Kuo / Preponderance of the Great' },
    { :bin => '010010', :number => "29", :name => 'K\'an / The Abysmal (Water)' },
    { :bin => '101101', :number => "30", :name => 'Li / The Clinging' },
    { :bin => '001110', :number => "31", :name => 'Hsien / Influence (Wooing)' },
    { :bin => '011100', :number => "32", :name => 'Heng / Duration' },
    { :bin => '001111', :number => "33", :name => 'TUN / Retreat' },
    { :bin => '111100', :number => "34", :name => 'Ta Chuang / The Power of the Great' },
    { :bin => '000101', :number => "35", :name => 'Chin / Progress' },
    { :bin => '101000', :number => "36", :name => 'Ming I / Darkening of the light' },
    { :bin => '101011', :number => "37", :name => 'Chia Jen / The Family [The Clan]' },
    { :bin => '110101', :number => "38", :name => 'K\'uei / Opposition' },
    { :bin => '001010', :number => "39", :name => 'Chien / Obstruction' },
    { :bin => '010100', :number => "40", :name => 'Hsieh / Deliverance' },
    { :bin => '110001', :number => "41", :name => 'Sun / Decrease' },
    { :bin => '100011', :number => "42", :name => 'I / Increase' },
    { :bin => '111110', :number => "43", :name => 'Kuai / Break-through (Resoluteness)' },
    { :bin => '011111', :number => "44", :name => 'Kou / Coming to Meet' },
    { :bin => '000110', :number => "45", :name => 'Ts\'ui / Gathering Together [Massing]' },
    { :bin => '011000', :number => "46", :name => 'Sheng / Pushing Upward' },
    { :bin => '010110', :number => "47", :name => 'K\'un / Oppression (Exhaustion)' },
    { :bin => '011010', :number => "48", :name => 'Ching / The Well' },
    { :bin => '101110', :number => "49", :name => 'Ko / Revolution (Molting)' },
    { :bin => '011101', :number => "50", :name => 'Ting / The Caldron' },
    { :bin => '100100', :number => "51", :name => 'Chen / The Arousing (Shock)' },
    { :bin => '001001', :number => "52", :name => 'Ken / Keeping Still' },
    { :bin => '001011', :number => "53", :name => 'Chien / Development (Gradual Progress)' },
    { :bin => '110100', :number => "54", :name => 'Kuei Mei / The Marrying Maiden' },
    { :bin => '101100', :number => "55", :name => 'Feng / Abundance [Fullness]' },
    { :bin => '001101', :number => "56", :name => 'Lu / The Wanderer' },
    { :bin => '011011', :number => "57", :name => 'Sun / The Gentle (The Penetrating)' },
    { :bin => '110110', :number => "58", :name => 'Tui / The Joyous' },
    { :bin => '010011', :number => "59", :name => 'Huan / Dispersion [Dissolution]' },
    { :bin => '110010', :number => "60", :name => 'Chieh / Limitation' },
    { :bin => '110011', :number => "61", :name => 'Chung Fu / Inner Truth' },
    { :bin => '001100', :number => "62", :name => 'Hsiao Kuo / Preponderance of the Small' },
    { :bin => '101010', :number => "63", :name => 'Chi Chi / After Completion' },
    { :bin => '010101', :number => "64", :name => 'Wei Chi / Before Completion' }
  ]
end
